- name: Ensure minimal deps are available
  ansible.builtin.package:
    name: "{{ item }}"
  become: true
  loop: "{{ default_vars.essential_pkgs }}"

- name: Gather OS specific variables
  ansible.builtin.include_vars:
    name: qemu
    file: "{{ ansible_os_family }}.yml"

- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ qemu.deps_pkgs }}"

- name: Install build dependencies for virtfs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ qemu.virtfs_pkgs }}"

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ qemu_url }}"
    dest: "{{ qemu_root }}"
    version: "{{ qemu_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
    recursive: false
  tags:
    - clone

- name: Build QEMU
  ansible.builtin.command: ./compile_qemu_nyx.sh static
  args:
    chdir: "{{ qemu_root }}"
  environment:
    CAPSTONE_ROOT: "{{ capstone_root }}"
    LIBXDC_ROOT: "{{ libxdc_root }}"
  when: not ansible_check_mode
  tags:
    - build
